# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from terminal_python_sdk.pydantic.connections_update_current_connection_details_request_company import ConnectionsUpdateCurrentConnectionDetailsRequestCompany
from terminal_python_sdk.pydantic.connections_update_current_connection_details_request_tags import ConnectionsUpdateCurrentConnectionDetailsRequestTags

class ConnectionsUpdateCurrentConnectionDetailsRequest(BaseModel):
    tags: typing.Optional[ConnectionsUpdateCurrentConnectionDetailsRequestTags] = Field(None, alias='tags')

    company: typing.Optional[ConnectionsUpdateCurrentConnectionDetailsRequestCompany] = Field(None, alias='company')

    external_id: typing.Optional[str] = Field(None, alias='externalId')

    status: typing.Optional[str] = Field(None, alias='status')

    sync_mode: typing.Optional[str] = Field(None, alias='syncMode')
    class Config:
        arbitrary_types_allowed = True
