# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from terminal_python_sdk import Terminal

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        terminal = Terminal(
        
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(terminal)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
