# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from terminal_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from terminal_python_sdk.api_response import AsyncGeneratorResponse
from terminal_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from terminal_python_sdk import schemas  # noqa: F401

from terminal_python_sdk.model.connections_create_custom_connection_request_company import ConnectionsCreateCustomConnectionRequestCompany as ConnectionsCreateCustomConnectionRequestCompanySchema
from terminal_python_sdk.model.connections_create_custom_connection_request import ConnectionsCreateCustomConnectionRequest as ConnectionsCreateCustomConnectionRequestSchema
from terminal_python_sdk.model.connections_create_custom_connection_request_tags import ConnectionsCreateCustomConnectionRequestTags as ConnectionsCreateCustomConnectionRequestTagsSchema
from terminal_python_sdk.model.connections_create_custom_connection_request_credentials import ConnectionsCreateCustomConnectionRequestCredentials as ConnectionsCreateCustomConnectionRequestCredentialsSchema
from terminal_python_sdk.model.connections_create_custom_connection_request_backfill import ConnectionsCreateCustomConnectionRequestBackfill as ConnectionsCreateCustomConnectionRequestBackfillSchema

from terminal_python_sdk.type.connections_create_custom_connection_request_backfill import ConnectionsCreateCustomConnectionRequestBackfill
from terminal_python_sdk.type.connections_create_custom_connection_request import ConnectionsCreateCustomConnectionRequest
from terminal_python_sdk.type.connections_create_custom_connection_request_tags import ConnectionsCreateCustomConnectionRequestTags
from terminal_python_sdk.type.connections_create_custom_connection_request_company import ConnectionsCreateCustomConnectionRequestCompany
from terminal_python_sdk.type.connections_create_custom_connection_request_credentials import ConnectionsCreateCustomConnectionRequestCredentials

from ...api_client import Dictionary
from terminal_python_sdk.pydantic.connections_create_custom_connection_request_tags import ConnectionsCreateCustomConnectionRequestTags as ConnectionsCreateCustomConnectionRequestTagsPydantic
from terminal_python_sdk.pydantic.connections_create_custom_connection_request_credentials import ConnectionsCreateCustomConnectionRequestCredentials as ConnectionsCreateCustomConnectionRequestCredentialsPydantic
from terminal_python_sdk.pydantic.connections_create_custom_connection_request_backfill import ConnectionsCreateCustomConnectionRequestBackfill as ConnectionsCreateCustomConnectionRequestBackfillPydantic
from terminal_python_sdk.pydantic.connections_create_custom_connection_request_company import ConnectionsCreateCustomConnectionRequestCompany as ConnectionsCreateCustomConnectionRequestCompanyPydantic
from terminal_python_sdk.pydantic.connections_create_custom_connection_request import ConnectionsCreateCustomConnectionRequest as ConnectionsCreateCustomConnectionRequestPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = ConnectionsCreateCustomConnectionRequestSchema


request_body_connections_create_custom_connection_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
_auth = [
    'bearerAuth',
]


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
)
_status_code_to_response = {
    '200': _response_for_200,
}


class BaseApi(api_client.Api):

    def _create_custom_connection_mapped_args(
        self,
        tags: typing.Optional[ConnectionsCreateCustomConnectionRequestTags] = None,
        backfill: typing.Optional[ConnectionsCreateCustomConnectionRequestBackfill] = None,
        company: typing.Optional[ConnectionsCreateCustomConnectionRequestCompany] = None,
        credentials: typing.Optional[ConnectionsCreateCustomConnectionRequestCredentials] = None,
        external_id: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        sync_mode: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if tags is not None:
            _body["tags"] = tags
        if backfill is not None:
            _body["backfill"] = backfill
        if company is not None:
            _body["company"] = company
        if credentials is not None:
            _body["credentials"] = credentials
        if external_id is not None:
            _body["externalId"] = external_id
        if provider is not None:
            _body["provider"] = provider
        if sync_mode is not None:
            _body["syncMode"] = sync_mode
        args.body = _body
        return args

    async def _acreate_custom_connection_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create Connection
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/connections',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_connections_create_custom_connection_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_custom_connection_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create Connection
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/connections',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_connections_create_custom_connection_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateCustomConnectionRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_custom_connection(
        self,
        tags: typing.Optional[ConnectionsCreateCustomConnectionRequestTags] = None,
        backfill: typing.Optional[ConnectionsCreateCustomConnectionRequestBackfill] = None,
        company: typing.Optional[ConnectionsCreateCustomConnectionRequestCompany] = None,
        credentials: typing.Optional[ConnectionsCreateCustomConnectionRequestCredentials] = None,
        external_id: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        sync_mode: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_custom_connection_mapped_args(
            tags=tags,
            backfill=backfill,
            company=company,
            credentials=credentials,
            external_id=external_id,
            provider=provider,
            sync_mode=sync_mode,
        )
        return await self._acreate_custom_connection_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_custom_connection(
        self,
        tags: typing.Optional[ConnectionsCreateCustomConnectionRequestTags] = None,
        backfill: typing.Optional[ConnectionsCreateCustomConnectionRequestBackfill] = None,
        company: typing.Optional[ConnectionsCreateCustomConnectionRequestCompany] = None,
        credentials: typing.Optional[ConnectionsCreateCustomConnectionRequestCredentials] = None,
        external_id: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        sync_mode: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_custom_connection_mapped_args(
            tags=tags,
            backfill=backfill,
            company=company,
            credentials=credentials,
            external_id=external_id,
            provider=provider,
            sync_mode=sync_mode,
        )
        return self._create_custom_connection_oapg(
            body=args.body,
        )

class CreateCustomConnection(BaseApi):

    async def acreate_custom_connection(
        self,
        tags: typing.Optional[ConnectionsCreateCustomConnectionRequestTags] = None,
        backfill: typing.Optional[ConnectionsCreateCustomConnectionRequestBackfill] = None,
        company: typing.Optional[ConnectionsCreateCustomConnectionRequestCompany] = None,
        credentials: typing.Optional[ConnectionsCreateCustomConnectionRequestCredentials] = None,
        external_id: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        sync_mode: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> None:
        raw_response = await self.raw.acreate_custom_connection(
            tags=tags,
            backfill=backfill,
            company=company,
            credentials=credentials,
            external_id=external_id,
            provider=provider,
            sync_mode=sync_mode,
            **kwargs,
        )
    
    
    def create_custom_connection(
        self,
        tags: typing.Optional[ConnectionsCreateCustomConnectionRequestTags] = None,
        backfill: typing.Optional[ConnectionsCreateCustomConnectionRequestBackfill] = None,
        company: typing.Optional[ConnectionsCreateCustomConnectionRequestCompany] = None,
        credentials: typing.Optional[ConnectionsCreateCustomConnectionRequestCredentials] = None,
        external_id: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        sync_mode: typing.Optional[str] = None,
        validate: bool = False,
    ) -> None:
        raw_response = self.raw.create_custom_connection(
            tags=tags,
            backfill=backfill,
            company=company,
            credentials=credentials,
            external_id=external_id,
            provider=provider,
            sync_mode=sync_mode,
        )


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        tags: typing.Optional[ConnectionsCreateCustomConnectionRequestTags] = None,
        backfill: typing.Optional[ConnectionsCreateCustomConnectionRequestBackfill] = None,
        company: typing.Optional[ConnectionsCreateCustomConnectionRequestCompany] = None,
        credentials: typing.Optional[ConnectionsCreateCustomConnectionRequestCredentials] = None,
        external_id: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        sync_mode: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_custom_connection_mapped_args(
            tags=tags,
            backfill=backfill,
            company=company,
            credentials=credentials,
            external_id=external_id,
            provider=provider,
            sync_mode=sync_mode,
        )
        return await self._acreate_custom_connection_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        tags: typing.Optional[ConnectionsCreateCustomConnectionRequestTags] = None,
        backfill: typing.Optional[ConnectionsCreateCustomConnectionRequestBackfill] = None,
        company: typing.Optional[ConnectionsCreateCustomConnectionRequestCompany] = None,
        credentials: typing.Optional[ConnectionsCreateCustomConnectionRequestCredentials] = None,
        external_id: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        sync_mode: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_custom_connection_mapped_args(
            tags=tags,
            backfill=backfill,
            company=company,
            credentials=credentials,
            external_id=external_id,
            provider=provider,
            sync_mode=sync_mode,
        )
        return self._create_custom_connection_oapg(
            body=args.body,
        )

