# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from terminal_python_sdk.paths.connections.post import CreateCustomConnectionRaw
from terminal_python_sdk.paths.connections_current.get import GetCurrentDetailsRaw
from terminal_python_sdk.paths.connections.get import ListAllRaw
from terminal_python_sdk.paths.connections_current.patch import UpdateCurrentConnectionDetailsRaw


class ConnectionsApiRaw(
    CreateCustomConnectionRaw,
    GetCurrentDetailsRaw,
    ListAllRaw,
    UpdateCurrentConnectionDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
