# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from terminal_python_sdk.paths.syncs_id.get import GetSyncStatusRaw
from terminal_python_sdk.paths.syncs.get import ListSyncHistoryRaw
from terminal_python_sdk.paths.passthrough.post import MakePassthroughRequestRaw
from terminal_python_sdk.paths.syncs.post import RequestSyncManualRaw


class DataManagementApiRaw(
    GetSyncStatusRaw,
    ListSyncHistoryRaw,
    MakePassthroughRequestRaw,
    RequestSyncManualRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
