# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from terminal_python_sdk.paths.syncs_id.get import GetSyncStatus
from terminal_python_sdk.paths.syncs.get import ListSyncHistory
from terminal_python_sdk.paths.passthrough.post import MakePassthroughRequest
from terminal_python_sdk.paths.syncs.post import RequestSyncManual
from terminal_python_sdk.apis.tags.data_management_api_raw import DataManagementApiRaw


class DataManagementApi(
    GetSyncStatus,
    ListSyncHistory,
    MakePassthroughRequest,
    RequestSyncManual,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DataManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DataManagementApiRaw(api_client)
