# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from terminal_python_sdk.paths.drivers_id.get import GetDetails
from terminal_python_sdk.paths.drivers.get import List
from terminal_python_sdk.apis.tags.drivers_api_raw import DriversApiRaw


class DriversApi(
    GetDetails,
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DriversApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DriversApiRaw(api_client)
