# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from terminal_python_sdk.paths.issues.get import ListObservedEventsRaw
from terminal_python_sdk.paths.issues_issue_id_resolve.post import MarkResolvedRaw


class IssuesApiRaw(
    ListObservedEventsRaw,
    MarkResolvedRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
