# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from terminal_python_sdk.paths.safety_events.get import GetEvents
from terminal_python_sdk.apis.tags.safety_api_raw import SafetyApiRaw


class SafetyApi(
    GetEvents,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SafetyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SafetyApiRaw(api_client)
