# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from terminal_python_sdk.paths.vehicles.get import GetAll
from terminal_python_sdk.paths.vehicles_id.get import GetDetails
from terminal_python_sdk.paths.vehicles_vehicle_id_stats_historical.get import GetHistoricalStats
from terminal_python_sdk.paths.vehicles_locations.get import GetLatestLocations
from terminal_python_sdk.paths.vehicles_vehicle_id_locations.get import ListHistoricalLocations
from terminal_python_sdk.apis.tags.vehicles_api_raw import VehiclesApiRaw


class VehiclesApi(
    GetAll,
    GetDetails,
    GetHistoricalStats,
    GetLatestLocations,
    ListHistoricalLocations,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VehiclesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VehiclesApiRaw(api_client)
