# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import terminal_python_sdk
from terminal_python_sdk.model.connections_create_custom_connection_request_backfill import ConnectionsCreateCustomConnectionRequestBackfill
from terminal_python_sdk import configuration


class TestConnectionsCreateCustomConnectionRequestBackfill(unittest.TestCase):
    """ConnectionsCreateCustomConnectionRequestBackfill unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
