# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from terminal_python_sdk import schemas  # noqa: F401


class ConnectionsUpdateCurrentConnectionDetailsRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def tags() -> typing.Type['ConnectionsUpdateCurrentConnectionDetailsRequestTags']:
                return ConnectionsUpdateCurrentConnectionDetailsRequestTags
        
            @staticmethod
            def company() -> typing.Type['ConnectionsUpdateCurrentConnectionDetailsRequestCompany']:
                return ConnectionsUpdateCurrentConnectionDetailsRequestCompany
            externalId = schemas.StrSchema
            status = schemas.StrSchema
            syncMode = schemas.StrSchema
            __annotations__ = {
                "tags": tags,
                "company": company,
                "externalId": externalId,
                "status": status,
                "syncMode": syncMode,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tags"]) -> 'ConnectionsUpdateCurrentConnectionDetailsRequestTags': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["company"]) -> 'ConnectionsUpdateCurrentConnectionDetailsRequestCompany': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["externalId"]) -> MetaOapg.properties.externalId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["syncMode"]) -> MetaOapg.properties.syncMode: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tags", "company", "externalId", "status", "syncMode", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tags"]) -> typing.Union['ConnectionsUpdateCurrentConnectionDetailsRequestTags', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["company"]) -> typing.Union['ConnectionsUpdateCurrentConnectionDetailsRequestCompany', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["externalId"]) -> typing.Union[MetaOapg.properties.externalId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["syncMode"]) -> typing.Union[MetaOapg.properties.syncMode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tags", "company", "externalId", "status", "syncMode", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        tags: typing.Union['ConnectionsUpdateCurrentConnectionDetailsRequestTags', schemas.Unset] = schemas.unset,
        company: typing.Union['ConnectionsUpdateCurrentConnectionDetailsRequestCompany', schemas.Unset] = schemas.unset,
        externalId: typing.Union[MetaOapg.properties.externalId, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        syncMode: typing.Union[MetaOapg.properties.syncMode, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConnectionsUpdateCurrentConnectionDetailsRequest':
        return super().__new__(
            cls,
            *args,
            tags=tags,
            company=company,
            externalId=externalId,
            status=status,
            syncMode=syncMode,
            _configuration=_configuration,
            **kwargs,
        )

from terminal_python_sdk.model.connections_update_current_connection_details_request_company import ConnectionsUpdateCurrentConnectionDetailsRequestCompany
from terminal_python_sdk.model.connections_update_current_connection_details_request_tags import ConnectionsUpdateCurrentConnectionDetailsRequestTags
