# coding: utf-8

# flake8: noqa

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from terminal_python_sdk.api_client import ApiClient

# import Configuration
from terminal_python_sdk.configuration import Configuration

# import exceptions
from terminal_python_sdk.exceptions import OpenApiException
from terminal_python_sdk.exceptions import ApiAttributeError
from terminal_python_sdk.exceptions import ApiTypeError
from terminal_python_sdk.exceptions import ApiValueError
from terminal_python_sdk.exceptions import ApiKeyError
from terminal_python_sdk.exceptions import ApiException

from terminal_python_sdk.client import Terminal
