# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from terminal_python_sdk.type.connections_create_custom_connection_request_company_dot_numbers import ConnectionsCreateCustomConnectionRequestCompanyDotNumbers

class RequiredConnectionsCreateCustomConnectionRequestCompany(TypedDict):
    pass

class OptionalConnectionsCreateCustomConnectionRequestCompany(TypedDict, total=False):
    dotNumbers: ConnectionsCreateCustomConnectionRequestCompanyDotNumbers

    name: str

class ConnectionsCreateCustomConnectionRequestCompany(RequiredConnectionsCreateCustomConnectionRequestCompany, OptionalConnectionsCreateCustomConnectionRequestCompany):
    pass
