# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from terminal_python_sdk.type.connections_create_custom_connection_request_backfill import ConnectionsCreateCustomConnectionRequestBackfill
from terminal_python_sdk.type.connections_create_custom_connection_request_company import ConnectionsCreateCustomConnectionRequestCompany
from terminal_python_sdk.type.connections_create_custom_connection_request_credentials import ConnectionsCreateCustomConnectionRequestCredentials
from terminal_python_sdk.type.connections_create_custom_connection_request_tags import ConnectionsCreateCustomConnectionRequestTags

class RequiredConnectionsCreateCustomConnectionRequest(TypedDict):
    pass

class OptionalConnectionsCreateCustomConnectionRequest(TypedDict, total=False):
    tags: ConnectionsCreateCustomConnectionRequestTags

    backfill: ConnectionsCreateCustomConnectionRequestBackfill

    company: ConnectionsCreateCustomConnectionRequestCompany

    credentials: ConnectionsCreateCustomConnectionRequestCredentials

    externalId: str

    provider: str

    syncMode: str

class ConnectionsCreateCustomConnectionRequest(RequiredConnectionsCreateCustomConnectionRequest, OptionalConnectionsCreateCustomConnectionRequest):
    pass
