# coding: utf-8

"""
    Terminal API

    Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDataManagementMakePassthroughRequestRequest(TypedDict):
    pass

class OptionalDataManagementMakePassthroughRequestRequest(TypedDict, total=False):
    body: str

    headers: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    method: str

    path: str

class DataManagementMakePassthroughRequestRequest(RequiredDataManagementMakePassthroughRequestRequest, OptionalDataManagementMakePassthroughRequestRequest):
    pass
